name:                iact-examples
version:             0.1.0.0
github:              "etellman/iact-examples"
license:             BSD-3-Clause
author:              "Edwin Tellman"
maintainer:          "etellman@pobox.com"
copyright:           "2023 Edwin Tellman"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/etellman/iact-examples#readme>

dependencies:
  - base >= 4.7 && < 5
  - partial-order >= 0.2.0.0
  - containers >= 0.6.7
  - approximate-equality >= 1.1.0.2
  - type-level-natural-number >= 2.0
  - slist >= 0.2.1.0
  - safe >= 0.3.14

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fwrite-ide-info
  - -hiedir=.hie

default-extensions:
  - MultiParamTypeClasses

library:
  source-dirs: src

tests:
  iact-examples-test:
    default-extensions:
      - OverloadedStrings
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iact-examples
    - hedgehog >= 1.1.2
    - tasty >= 1.4.3
    - tasty-hedgehog >= 0.2.0.0
    - tasty-hunit >= 0.10
